spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/pet_management_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  docker:
    compose:
      enabled: true

springdotenv:
  enabled: true
  filename: .env.dev