### Request authentication
POST {{host}}/api/auth/request
Content-Type: application/json

{
  "email": "chris.jones@example.com"
}

### Verify authentication
POST {{host}}/api/auth/verify
Content-Type: application/json

{
  "email": "chris.jones@example.com",
  "code": ""
}
