### Create
POST {{host}}/api/owners
Content-Type: application/json

{
  "name": "Chris Jones",
  "email": "chris.jones@example.com",
  "phone": "+1 (903) 744-6133"
}

### Me
GET {{host}}/api/owners/me
Authorization: Bearer {{token}}

### Update
PUT {{host}}/api/owners/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Chris Jones",
  "email": "c.jones@example.com",
  "phone": "+1 (954) 981-1015"
}
